#!/usr/bin/env python

""" 
Copyright 2013 Mohammad Razavi <mrazavi64-at-gmail-dot-com>
 
This software is distributed AS IT IS. Use at your own risk. 
If it borks your system, you have  been forewarned. 
 
This software is licensed under the LGPL Version 3 
http://www.gnu.org/licenses/lgpl-3.0.txt
"""

import sys
from optparse import OptionParser
from collections import OrderedDict

def PrintTimesheet(timesheet, ID):
    sys.stdout.write("%s\n" % ID)
    for date, times in timesheet[ID].iteritems():
        first = True
        last_direction = 1
        
        for direction, t in times:
            if first:
                sys.stdout.write("%s" % date)
                first = False
            elif last_direction != 0:
                sys.stdout.write("--------")
                
            if direction == 0:
                if last_direction == 0:
                    sys.stdout.write("\t-----\n--------")
                sys.stdout.write("\t%s" % t)
            else:
                if last_direction == 1:
                    sys.stdout.write("\t-----")
                sys.stdout.write("\t%s\n" % t)

            last_direction = direction
            
        if last_direction == 0:
            sys.stdout.write("\t-----\n")

    sys.stdout.write("\n")

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-a", "--all", dest = "all", \
                      action = "store_true", default = False, \
                      help = "Decode all the IDs")
    parser.add_option("-i", "--ID", dest="IDs",
                      action = "append", type = "int", \
                      help = "Decode the specified ID")
    parser.set_usage("%s [OPTION]... TIMESHEET-FILE\n" % sys.argv[0])

    OPTIONS, ARGS = parser.parse_args()

    if len(ARGS) != 1:
        sys.stderr.write("You have to specify the timesheet file.\n")
        exit(1)

    timesheet = {}

    current_date = "00/00/00"

    with open(ARGS[0]) as fp:
        for line in fp:
            line = line.strip()

            if line.startswith("0" * 8):
                current_date = "%s/%s/%s" % \
                               (line[8:10], line[10:12], line[12:14])
            elif line.startswith("00") and \
                 (line.endswith("00") or line.endswith("08")):
                ID = line[2:8]
                t = "%s:%s" % (line[8:10], line[10:12])
                direction = 1 if line[12:14] == "08" else 0

                timesheet.setdefault(ID, OrderedDict()) \
                         .setdefault(current_date, []) \
                         .append((direction, t))

    if OPTIONS.IDs and not OPTIONS.all:
        for ID in OPTIONS.IDs:
            PrintTimesheet(timesheet, str(ID))
    else:
        for ID in timesheet.keys():
            PrintTimesheet(timesheet, ID)
